---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: glasskube-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: glasskube-operator
subjects:
  - kind: ServiceAccount
    name: {{ template "glasskube-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
