apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - role.yaml
  - role-binding.yaml
patches:
  - target:
      kind: Deployment
      name: glasskube-operator
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
         - name: MANAGE_CURRENT_NAMESPACE
           value: 'true'
