name: Feature Request
description: Suggest and idea for this project
title: "[Feature]: <Feature Request Title>"
labels: ["type:feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for initiating this feature request !🤗
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: "Please check the following before submitting this feature request"
      options:
        - label: I've searched for similar issues and couldn't find anything matching
          required: true

  - type: dropdown
    id: problem
    attributes:
      label: Is this feature request related to a problem?
      options:
        - "Yes"
        - "No"
  - type: textarea
    id: problem_description
    attributes:
      label: Problem Description
      description: If yes, please provide a clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: solution_description
    attributes:
      label: Solution Description
      description: A clear and concise description of what you want to happen
    validations:
      required: true
  - type: textarea
    id: benefits_description
    attributes:
      label: Benefits
      description: Describe the benefits this feature will bring to the project and its users
    validations:
      required: true
  - type: textarea
    id: drawbacks
    attributes:
      label: Potential Drawbacks
      description: Describe any potential drawbacks this feature might bring to the project and its users.
  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: Add any other context about your feature request here. If applicable, add drawings to help explain.
