name: Main

on:
  push:
    branches:
      - main
    paths-ignore:
      - docs/**

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          java-version: 17
          distribution: zulu
      - uses: gradle/actions/setup-gradle@cc4fc85e6b35bafd578d5ffbc76a5518407e1af0 # v4.2.1
        with:
          dependency-graph: generate-and-submit
      - name: Java build
        run: ./gradlew assemble
      - name: Tests
        run: ./gradlew test
        env:
          GITHUB_DEPENDENCY_GRAPH_ENABLED: false
      - name: Lint
        run: ./gradlew --continue ktlintCheck
        env:
          GITHUB_DEPENDENCY_GRAPH_ENABLED: false
